/**
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS-IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// This file is automatically generated

package com.google.livingstories.client.lsp;

/**
 * Interface to represent the constants contained in resource bundle:
 * 	'LspConstants.properties'.
 */
public interface LspConstants extends com.google.gwt.i18n.client.Constants {
  
  /**
   * Translated "Standard view".
   * 
   * @return translated "Standard view"
   */
  @DefaultStringValue("Standard view")
  @Key("allImportance")
  String allImportance();

  /**
   * Translated "All Coverage".
   * 
   * @return translated "All Coverage"
   */
  @DefaultStringValue("All Coverage")
  @Key("allThemes")
  String allThemes();

  /**
   * Translated "All".
   * 
   * @return translated "All"
   */
  @DefaultStringValue("All")
  @Key("allTypes")
  String allTypes();

  /**
   * Translated "No items found".
   * 
   * @return translated "No items found"
   */
  @DefaultStringValue("No items found")
  @Key("contentItemListNoItemsText")
  String contentItemListNoItemsText();

  /**
   * Translated "Default view".
   * 
   * @return translated "Default view"
   */
  @DefaultStringValue("Default view")
  @Key("defaultView")
  String defaultView();

  /**
   * Translated "Most important only".
   * 
   * @return translated "Most important only"
   */
  @DefaultStringValue("Most important only")
  @Key("highImportance")
  String highImportance();

  /**
   * Translated "Image is unavailable; sorry!".
   * 
   * @return translated "Image is unavailable; sorry!"
   */
  @DefaultStringValue("Image is unavailable; sorry!")
  @Key("imageUnavailable")
  String imageUnavailable();

  /**
   * Translated "Location".
   * 
   * @return translated "Location"
   */
  @DefaultStringValue("Location")
  @Key("locationTitle")
  String locationTitle();

  /**
   * Translated "Newest first".
   * 
   * @return translated "Newest first"
   */
  @DefaultStringValue("Newest first")
  @Key("newestFirst")
  String newestFirst();

  /**
   * Translated "Oldest first".
   * 
   * @return translated "Oldest first"
   */
  @DefaultStringValue("Oldest first")
  @Key("oldestFirst")
  String oldestFirst();

  /**
   * Translated "Read other Living Stories:".
   * 
   * @return translated "Read other Living Stories:"
   */
  @DefaultStringValue("Read other Living Stories:")
  @Key("otherStories")
  String otherStories();

  /**
   * Translated "Read more...".
   * 
   * @return translated "Read more..."
   */
  @DefaultStringValue("Read more...")
  @Key("readMore")
  String readMore();

  /**
   * Translated "Failed to load timeline content".
   * 
   * @return translated "Failed to load timeline content"
   */
  @DefaultStringValue("Failed to load timeline content")
  @Key("recentEventsListProblem")
  String recentEventsListProblem();

  /**
   * Translated "Timeline of important events".
   * 
   * @return translated "Timeline of important events"
   */
  @DefaultStringValue("Timeline of important events")
  @Key("recentEventsListTitle")
  String recentEventsListTitle();

  /**
   * Translated "Related".
   * 
   * @return translated "Related"
   */
  @DefaultStringValue("Related")
  @Key("related")
  String related();

  /**
   * Translated "Set as default view".
   * 
   * @return translated "Set as default view"
   */
  @DefaultStringValue("Set as default view")
  @Key("setAsDefault")
  String setAsDefault();

  /**
   * Translated "Show less".
   * 
   * @return translated "Show less"
   */
  @DefaultStringValue("Show less")
  @Key("showLess")
  String showLess();

  /**
   * Translated "[source]".
   * 
   * @return translated "[source]"
   */
  @DefaultStringValue("[source]")
  @Key("sourceLinkText")
  String sourceLinkText();

  /**
   * Translated "View more".
   * 
   * @return translated "View more"
   */
  @DefaultStringValue("View more")
  @Key("viewMore")
  String viewMore();

  /**
   * Translated "Problem receiving new updates. Please try again.".
   * 
   * @return translated "Problem receiving new updates. Please try again."
   */
  @DefaultStringValue("Problem receiving new updates. Please try again.")
  @Key("viewMoreProblem")
  String viewMoreProblem();
}
