#!/bin/sh

if [ ! $SDKJAR ]
then
  echo 'SDKJAR environment variable not defined. It needs to be defined for this builder to run.'
  exit 1
fi

for script in *-i18n
do
  ./$script
done

./sanify-autogenerated-files.sh
