#!/bin/bash

# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Fixes up the files that are automatically generated by the i18n scripts
# so that they don't exceed 100-char-length lines, and they include a copyright
# line and note that the file is autogenerated.

rm -f temp.txt
files=`hg status -mn | grep '[a-zA-Z]\(Constants\|Messages\).java'`

for file in $files
do
  if ! head -n 2 $file | tail -n 1 | grep -q '^ * Copyright'
  then
    echo Sanifying $file
    cat > temp.txt <<EOF
/**
 * Copyright `date +%Y` Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS-IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// This file is automatically generated

EOF
    cat $file >> temp.txt
    sed "s|/.*/\(.*\)\.properties|\1.properties|" < temp.txt > $file
  fi
done
if [ -a temp.txt ]
then
  rm temp.txt
  echo Done
else
  echo 'No work to do. Thanks for running me!'
fi
