/**
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS-IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// This file is automatically generated

package com.google.livingstories.client;

/**
 * Interface to represent the constants contained in resource bundle:
 * 	'ClientConstants.properties'.
 */
public interface ClientConstants extends com.google.gwt.i18n.client.Constants {
  
  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("assetNavLinkStringAudio")
  String assetNavLinkStringAudio();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("assetNavLinkStringDocuments")
  String assetNavLinkStringDocuments();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("assetNavLinkStringImages")
  String assetNavLinkStringImages();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("assetNavLinkStringInteractives")
  String assetNavLinkStringInteractives();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("assetNavLinkStringLinks")
  String assetNavLinkStringLinks();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("assetNavLinkStringVideos")
  String assetNavLinkStringVideos();

  /**
   * Translated "By".
   * 
   * @return translated "By"
   */
  @DefaultStringValue("By")
  @Key("bylineLeadinBaseContentItem")
  String bylineLeadinBaseContentItem();

  /**
   * Translated "As reported by".
   * 
   * @return translated "As reported by"
   */
  @DefaultStringValue("As reported by")
  @Key("bylineLeadinQuoteContentItem")
  String bylineLeadinQuoteContentItem();

  /**
   * Translated "Opinion".
   * 
   * @return translated "Opinion"
   */
  @DefaultStringValue("Opinion")
  @Key("contentFilterNameNarrativeOpinion")
  String contentFilterNameNarrativeOpinion();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentFilterStringData")
  String contentFilterStringData();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentFilterStringEvents")
  String contentFilterStringEvents();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentFilterStringNarratives")
  String contentFilterStringNarratives();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentFilterStringPlayers")
  String contentFilterStringPlayers();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentFilterStringQuotes")
  String contentFilterStringQuotes();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentNavLinkStringAssets")
  String contentNavLinkStringAssets();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentNavLinkStringData")
  String contentNavLinkStringData();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentNavLinkStringEvents")
  String contentNavLinkStringEvents();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentNavLinkStringPlayers")
  String contentNavLinkStringPlayers();

  /**
   * Translated "".
   * 
   * @return translated ""
   */
  @DefaultStringValue("")
  @Key("contentNavLinkStringReactions")
  String contentNavLinkStringReactions();

  /**
   * Translated "Concept".
   * 
   * @return translated "Concept"
   */
  @DefaultStringValue("Concept")
  @Key("contentTypeStringConcept")
  String contentTypeStringConcept();

  /**
   * Translated "Details".
   * 
   * @return translated "Details"
   */
  @DefaultStringValue("Details")
  @Key("contentTypeStringEvent")
  String contentTypeStringEvent();

  /**
   * Translated "High".
   * 
   * @return translated "High"
   */
  @DefaultStringValue("High")
  @Key("importanceHigh")
  String importanceHigh();

  /**
   * Translated "Low".
   * 
   * @return translated "Low"
   */
  @DefaultStringValue("Low")
  @Key("importanceLow")
  String importanceLow();

  /**
   * Translated "Medium".
   * 
   * @return translated "Medium"
   */
  @DefaultStringValue("Medium")
  @Key("importanceMedium")
  String importanceMedium();

  /**
   * Translated "New Content Item".
   * 
   * @return translated "New Content Item"
   */
  @DefaultStringValue("New Content Item")
  @Key("newContentItemDisplayString")
  String newContentItemDisplayString();

  /**
   * Translated "Organization".
   * 
   * @return translated "Organization"
   */
  @DefaultStringValue("Organization")
  @Key("playerDisplayNameOrganization")
  String playerDisplayNameOrganization();

  /**
   * Translated "Person".
   * 
   * @return translated "Person"
   */
  @DefaultStringValue("Person")
  @Key("playerDisplayNamePerson")
  String playerDisplayNamePerson();

  /**
   * Translated "Unable to load data. Please try again.".
   * 
   * @return translated "Unable to load data. Please try again."
   */
  @DefaultStringValue("Unable to load data. Please try again.")
  @Key("startPageLoadFailed")
  String startPageLoadFailed();

  /**
   * Translated "Living Stories".
   * 
   * @return translated "Living Stories"
   */
  @DefaultStringValue("Living Stories")
  @Key("startPageTitle")
  String startPageTitle();

  /**
   * Translated "View all »".
   * 
   * @return translated "View all »"
   */
  @DefaultStringValue("View all »")
  @Key("startPageViewAll")
  String startPageViewAll();
}
